### ISSUE TITLE
Feature request: layer as a style option

### ISSUE THREAD

**Issue by akvadrako** [emersion/mako#210] opened 2019-12-21 15:25 UTC
I would like important notifications to be displayed with layer=overlay and other notifications with layer=top.

**Comment by vilhalmer** [comment] 2019-12-22 13:26
Duplicate of #183, though the title of this one is clearer. See also #123, #200 for other things that would require splitting apart notifications onto multiple layer surfaces.

**Comment by vilhalmer** [comment] 2020-06-18 13:12
This will be possible after #228.

**Comment by emersion** [comment] 2020-06-23 10:49
Fixed in #228

**Closed by emersion** 2020-06-23 10:49 UTC
