### ISSUE TITLE
Format specifier for timestamp

### ISSUE THREAD

**Issue by gergelypolonkai** [emersion/mako#350] opened 2021-05-06 03:26 UTC
It often happens to me that i leave my machine running for the night, and when i wake up there are a bunch of notifications. Most of the time i can derive the time of the event from the notification itself, but sometimes i can’t, but it would be good to know when a specific event happened.

It would be great if i could add something like `%t` to my format text, so i could see this information.

**Comment by vilhalmer** [comment] 2021-05-06 03:44
Duplicate of #272.

**Closed by vilhalmer** 2021-05-06 03:44 UTC
