### ISSUE TITLE
Mako stops displaying notifications when switching between monitor layouts

### ISSUE THREAD

**Issue by MichaelAquilina** [emersion/mako#189] opened 2019-09-29 17:45 UTC
I don't have a minimal set of reproducible steps yet, but I have noticed pretty consistently that whenever I change from using my external monitor, to using my laptop monitor and then back again to my external - then mako stops showing notifications.

The only way I've managed to work round this problem is by killing mako and re-starting the process.

**Comment by emersion** [comment] 2019-09-29 18:07
This is likely a Sway issue. Would be nice to have reproducible steps.

**Comment by MichaelAquilina** [comment] 2019-10-01 13:41
Will try come up with some minimal reproducible steps tonight if I get the chance!

**Comment by tbm** [comment] 2019-12-13 15:39
mako also stops showing notifications here from time to time (the mako binary is still running iirc). Unfortunately I haven't identified a pattern so far.  But I do connect an external monitor so maybe it's related.

@MichaelAquilina have you found a way to reproduce this yet?

**Comment by MichaelAquilina** [comment] 2019-12-13 15:42
I actually haven't managed to find a minimal test case yet :( I definitely notice it more often when switching monitor states though

**Comment by emersion** [comment] 2019-12-13 15:44
Anything in stderr?

Do disconnected monitors still appear as connected in `swaymsg -t get_outputs`? If so, maybe mako does show notifications on a disconnected screen.

**Comment by tbm** [comment] 2019-12-13 15:55
* Simon Ser <notifications@github.com> [2019-12-13 07:44]:
> Anything in stderr?
> 
> Do disconnected monitors still appear as connected in `swaymsg -t get_outputs`? If so, maybe mako does show notifications on a disconnected screen.

The disconnected screens do not show up in `swaymsg -t get_outputs` in
my case.

I just tried connecting and disconnecting a few times and wasn't able
to reproduce it.

I changed my sway config so mako's output is now stored in a file, so
maybe something will be there if/when it happens again.

**Comment by tbm** [comment] 2019-12-13 22:59
I'm not sure when mako stopped running but it's not running anymore.  I had a lot of sway crashes today because my external monitor can be unreliable and that causes a sway crash.  But mako is started in sway's config, so I don't think that matters for this issue here.

I see this in the log file:

```
wl_registry@2: error 0: invalid global wl_output (33)
failed to read Wayland events
wl_registry@2: error 0: invalid global wl_output (28)
```

I earlier said that mako is still running when it happens, but it's not running now.

**Comment by emersion** [comment] 2019-12-14 01:20
>wl_registry@2: error 0: invalid global wl_output (28)

Yet another bug fixed by https://github.com/swaywm/wlroots/pull/1765

**Comment by kennylevinsen** [comment] 2020-03-27 13:58
Can this still be reproduced with master as of https://github.com/emersion/mako/commit/068e81d4e6c721ef60d1ba660098b885a6124fa4?

**Comment by tbm** [comment] 2020-03-27 14:02
I don't have access to an external monitor at the moment.  Maybe someone else can confirm.

**Comment by MichaelAquilina** [comment] 2020-03-27 15:04
Tried building mako from the latest commit 068e81d4e6c721ef60d1ba660098b885a6124fa4 and I still could reproduce the bug.

steps:
0) Connect external monitor, disable internal monitor
1) Start mako
2) verify mako is working with `notify-send hello`
3) disconnect external monitor
4) reconnect external monitor
5) run `notify-send hello` and confirm no notification is shown

**Comment by emersion** [comment] 2020-03-27 15:06
Do you have `output` in  your config?

**Comment by MichaelAquilina** [comment] 2020-03-27 15:07
```
default-timeout=7000
background-color=#262626
format=%a\n<b>%s</b>\n%b
height=200
width=450

[urgency="high"]
background-color=#ff0000
```

This is my config in `~/.config/mako/config`

**Comment by MichaelAquilina** [comment] 2020-03-27 15:12
Tried seeing if I could reproduce this by disable my external monitor and then re-enabling it but it doesnt seem to show the same issue:

```
swaymsg output DP-2 disable && sleep 4 && swaymsg output DP-2 enable 
notify-send hello  # still works
```

**Comment by kennylevinsen** [comment] 2020-03-27 15:34
I can reproduce by:
1. Having a single external monitor enabled
2. Disconnecting it and turning it *off* (seems to be required)
3. Connecting it and turning it back on.

I'm stuck with a dirty state with no frame callback, which will block any further attempts at rendering. Possible that there are more paths that lack cleanup.

**Comment by MichaelAquilina** [comment] 2020-03-27 15:47
> Disconnecting it and turning it off (seems to be required)

In my case I dont need to turn my monitor off

**Comment by kennylevinsen** [comment] 2020-03-27 16:19
Can you try https://github.com/emersion/mako/pull/251? It fixes this issue for me.

**Comment by MichaelAquilina** [comment] 2020-03-27 16:24
Can confirm that PR fixes the bug :)

**Closed** 2020-03-27 20:31 UTC
