### ISSUE TITLE
Allow interactive prompt

### ISSUE THREAD

**Issue by 1wxyz** [emersion/mako#172] opened 2019-07-05 07:00 UTC
Currently, if using bluetooth to receive files or device pairings, it is able to prompt the message via mako but couldn't prompt interactive buttons like "Accept"/"Reject" or "OK"/"Cancel".

**Comment by emersion** [comment] 2019-07-05 07:00
Duplicate of https://github.com/emersion/mako/issues/4

**Closed by emersion** 2019-07-05 07:00 UTC
