### ISSUE TITLE
display notification permanently

### ISSUE THREAD

**Issue by copypaste10** [emersion/mako#173] opened 2019-07-07 21:16 UTC
Hello,

how can I get mako to display a certain notification permanently? (until I manually delete notifications)
It's needed only for Evolution. The reminders function of Evolution sends a notification with "Reminders" title.

**Comment by vilhalmer** [comment] 2019-07-07 21:29
```
[app-name=Evolution]  # Or whatever you want to select on
ignore-timeout=true
default-timeout=0```

**Comment by copypaste10** [comment] 2019-07-07 21:50
Thanks. I will try it.

**Comment by copypaste10** [comment] 2019-07-08 13:15
I don't get it but this somehow affects all notifications, not only Evolution/Reminders. They all appear persistently until I click on them.

Sections like
[app-name=Evolution]
...
...

are only applied to all notifications, not just Evolution

**Comment by vilhalmer** [comment] 2019-07-12 23:34
Sorry for the delayed response.

I can't reproduce this issue, if I use those lines with e.g. `[app-name=notify-send]` the notification will stick around forever. Last time someone experienced an issue like this it was because the application sending the notification was itself closing the notification after some period of time. I don't have Evolution to determine if this is the case, but it might be worth looking through its configuration or code.

**Comment by TheAvidDev** [comment] 2020-09-28 15:50
I can't reproduce this either. Perhaps you set:
```yml
default-timeout=0```
in a global setting?

**Comment by vilhalmer** [comment] 2021-01-31 23:14
Closing due to no feedback.

**Closed by vilhalmer** 2021-01-31 23:14 UTC
