### ISSUE TITLE
Failed to connect to user bus: Permission denied

### ISSUE THREAD

**Issue by Sunderland93** [emersion/mako#257] opened 2020-04-11 07:28 UTC
Hello. I'm running Sway 1.4 on Kubuntu 20.04. I put `exec mako` in Sway's config, but it doesn't work. When I manually start Mako, it gives an error `Failed to connect to user bus: Permission denied`

**Comment by luispabon** [comment] 2020-04-24 11:57
I'm having the same problem on Ubuntu 20.04. I reckon it's an ubuntu problem, and recent - I had my notifications working until recently (I upgraded to 20.04 a month ago). Any idea what to look for debugging this @emersion ? Might have to report it to ubuntu itself.

**Comment by luispabon** [comment] 2020-04-24 12:49
@Sunderland93 I discovered I had `mate-notification-daemon` running for some weird reason (I don't recall installing any mate components) which was preventing mako from working. After uninstalling it and logging back in mako started working again.

**Comment by DanSnow** [comment] 2020-04-27 15:29
I'm having the same problem on Ubuntu 20.04. And this seems an issue related to AppArmor. I just disable the rule for mako and it's working.
```shell
$ sudo aa-disable /etc/apparmor.d/fr.emersion.Mako
```

**Comment by luitzifa** [comment] 2020-04-28 09:06
I can confirm its related to AppArmor in Ubuntu 20.04 .

**Comment by emersion** [comment] 2020-04-28 09:07
Closing because this is a distribution issue. We already have an AppArmor file: https://github.com/emersion/mako/tree/master/contrib/apparmor

**Closed by emersion** 2020-04-28 09:07 UTC

**Comment by stevenengler** [comment] 2020-07-20 22:08
Just as a note for 20.04: the apparmor error for the mako message `Failed to connect to user bus: Permission denied` is:

```
audit: type=1400 audit([snip]): apparmor="DENIED" operation="connect" profile="fr.emersion.Mako" name="/run/user/1000/bus" pid=1737548 comm="mako" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000
```

I added the line `/run/user/*/bus rw,` to `local/fr.emersion.Mako`, but this is not quite enough to fix the problem since after reloading the profile, the new error is `Failed to acquire service name: Permission denied`. This time apparmor does not log any errors, but disabling the apparmor profile for mako altogether fixes the problem.

**Comment by BNolet** [comment] 2020-09-27 19:58
Just a tip for some, if you get `sudo: aa-disable: command not found`, install `apparmor-utils` with `sudo apt install apparmor-utils`

**Comment by fbo25** [comment] 2020-12-14 09:35
**Ubuntu 20.10 workaround**

1. Uncomment line 22 in /etc/apparmor.d/fr.emersion.Mako :
`include if exists <local/fr.emersion.Mako>`

2. Create file /etc/apparmor.d/local/fr.emersion.Mako
3. ...and add the following lines :
```
  owner @{run}/user/[0-9]*/bus rw,
  dbus send
       bus=session
       path=/org/freedesktop/DBus
       interface=org.freedesktop.DBus
       member={Hello,RequestName}
       peer=(name=org.freedesktop.DBus),
  dbus (receive)
       bus=session
       path=/org/freedesktop/Notifications
       interface=org.freedesktop.Notifications
       member={Notify,NotificationClosed,GetServerInformation,GetCapabilities},
```
4. Restart apparmor service :
`sudo systemctl restart apparmor`

**Comment by apiraino** [comment] 2020-12-23 14:51
Same issue on debian bullseye, the workaround works. I'd like to report this to the package maintainer, but I'm confused on what the fix should be on the distribution package. Can anyone clarify this?

thanks

**Comment by fbo25** [comment] 2020-12-29 12:58
Quick update of the workaround, because the notifications were not closed automatically : 
`owner @{run}/user/[0-9]*/bus rw,
  dbus send
       bus=session
       path=/org/freedesktop/DBus
       interface=org.freedesktop.DBus
       member={Hello,RequestName}
       peer=(name=org.freedesktop.DBus),
  dbus (send)
       bus=session
       path=/org/freedesktop/Notifications
       interface=org.freedesktop.Notifications
       member=NotificationClosed,
  dbus (receive)
       bus=session
       path=/org/freedesktop/Notifications
       interface=org.freedesktop.Notifications
       member={Notify,NotificationClosed,GetServerInformation,GetCapabilities,CloseNotification},
      `

**Comment by x10an14** [comment] 2021-01-29 09:28
> @emersion: Closing because this is a distribution issue. We already have an AppArmor file: https://github.com/emersion/mako/tree/master/contrib/apparmor

Replacing `/etc/apparmor.d/fr.emersion.Mako` with the one referenced in this repo didn't make it work for me.
Copy-pasting the lines from https://github.com/emersion/mako/issues/257#issuecomment-752066251 into the existing file `/etc/apparmor.d/fr.emersion.Mako` however, worked for me.

I'm running Linux Mint 20.1 - based of off Ubuntu 20.04, and installed the original file with the `apparmor-profiles-extra` package.

**Comment by SuperBo** [comment] 2021-04-19 08:22
Thank @fbo25. His approach works for me on Ubuntu 20.04.

**Comment by karlmdavis** [comment] 2022-02-23 18:33
This line failed for me, on Ubuntu 20.04:

> ```
>   owner @{run}/user/[0-9]*/bus rw,
> ```

Produced this error when trying to reload/apply the profile:

```
$ sudo apparmor_parser -r /etc/apparmor.d/fr.emersion.Mako 
Found reference to variable run, but is never declared
```

Instead, I left the `/etc/apparmor.d/fr.emersion.Mako` file alone (the `#` doesn't comment out the `include`, it's part of the `#include` directive) and just created `/etc/apparmor.d/local/fr.emersion.Mako` with the following contents:

```
  owner /run/user/[0-9]*/bus rw,
  dbus send
       bus=session
       path=/org/freedesktop/DBus
       interface=org.freedesktop.DBus
       member={Hello,RequestName}
       peer=(name=org.freedesktop.DBus),
  dbus (send)
       bus=session
       path=/org/freedesktop/Notifications
       interface=org.freedesktop.Notifications
       member=NotificationClosed,
  dbus (receive)
       bus=session
       path=/org/freedesktop/Notifications
       interface=org.freedesktop.Notifications
       member={Notify,NotificationClosed,GetServerInformation,GetCapabilities,CloseNotification},
```

This takes `mako` from failing with this error:

```
$ mako
Failed to connect to user bus: Permission denied
```

To instead working as expected. Yay!

**Comment by gerardparareda** [comment] 2023-05-11 13:18
I am also facing this same issue on Ubuntu 22.04.

**Comment by xe2io** [comment] 2023-07-17 19:53
For those using Ubuntu 22.04 (I also ran into this issue :P)- the issue is that the packaged `mako-notifier` version (1.6-2 at time of writing) still contains the apparmor profile, even though it was removed (https://github.com/emersion/mako/issues/378#issuecomment-1136003563).
  
Two options:
#### add local config to `/etc/apparmor.d/local/fr.emerson.Mako`
This file is sourced by the packaged profile, and you'll need to add a combination of https://github.com/emersion/mako/issues/257#issuecomment-1049087860 and https://github.com/emersion/mako/issues/378#issuecomment-1077932960 to workaround the 
`Failed to acquire service name: Permission denied` dbus error and to allow your symlinked config path.
  
Reload the profile:
```
sudo apparmor_parser -r /etc/apparmor.d/fr.emerson.Mako
```

#### Disable the fr.emerson.Mako apparmor profile
Unload the mako profile:
```
sudo apparmor_parser -R /etc/apparmor.d/fr.emersion.Mako
```
symlink fr.emerson.Mako to the disable folder for persistence:
```
sudo ln -s /etc/apparmor.d/fr.emersion.Mako /etc/apparmor.d/disable/
```
(I'm not that familiar with apparmor- you may be able to just delete the profile so it's never loaded instead of symlinking it to the disable folder, but it looks like one needs to at least unload with `apparmor_parser -R` regardless of stopping/restarting the apparmor service.)
  
Hope this helps anyone running into the same issue!
