### ISSUE TITLE
[Feature Request] makoctl command for opening previously closed notification

### ISSUE THREAD

**Issue by MichaelAquilina** [emersion/mako#179] opened 2019-07-19 12:34 UTC
I often close a notification by mistake and immediately wish to re-show it. It would be nice if there was a way to open previously closed notifications.

This is very similar to the history feature in Dunst https://dunst-project.org/

**Comment by emersion** [comment] 2019-07-19 12:39
Duplicate of https://github.com/emersion/mako/issues/91

**Closed by emersion** 2019-07-19 12:39 UTC
