### ISSUE TITLE
Add the ability to temporary disable/pause notifications

### ISSUE THREAD

**Issue by asahaf** [emersion/mako#284] opened 2020-07-07 17:12 UTC
Hi,

I would be great if we have the ability with IPC to temporary disable/pause notifications (don't disturb), for example during meetings. 

Thanks,

**Comment by emersion** [comment] 2020-07-07 17:12
Duplicate of https://github.com/emersion/mako/issues/138

**Closed by emersion** 2020-07-07 17:12 UTC

**Comment by dafeder** [comment] 2024-01-12 16:09
Could you point us more specifically to how this is currently accomplished in mako?

**Comment by dafeder** [comment] 2024-01-12 16:52
Update - for people who this hasn't been intuitive for, you need to add a do-not-disturb mode with invisible=true, and enable/disable that mode. So:

```
[mode=do-not-disturb]
invisible=1
```
then
`makoctl mode -a do-not-disturb`
or
`makoctl mode -r do-not-disturb`
